### ISSUE TITLE
Setup guide for Ubuntu

### ISSUE THREAD

**Issue by ntulip** [austinthecoder/pinger#1]
Hi

Having a bit of a hard time getting rake db:migrate to mysql working. Possible you could have an installation guide for pinger? I know basically nothing about rails so it's hard to get it to work. One problem I ran into is no database.yml as well.

Here is the error in question:

> ~/pinger$ rake db:migrate
> rake aborted!
> You have a nil object when you didn't expect it!
> You might have expected an instance of Array.
> The error occurred while evaluating nil.[]
> 
> Tasks: TOP => db:migrate => environment
> (See full trace by running task with --trace)

Running it with trace produces a lot of code but only the first lines after the above message seems related to the project. I've dumped the whole output here: http://pastebin.com/MbBhcahU

> /home/my_user_name/pinger/config/initializers/resque.rb:4:in `<top (required)>'
> /home/my_user_name/pinger/config/environment.rb:5:in`<top (required)>'

**Comment by mensfeld** [comment]
The CONFIG didn't work for me as well. Instead try using a gem like settingslogic to manage your settings. Then the code would look like:

``` ruby
require 'resque_scheduler'

Resque.redis = Redis.new(
  host: Settings.redis.host,
  port: Settings.redis.port,
  password: Settings.redis.password,
  thread_safe: true
)

Resque::Server.use Rack::Auth::Basic do |user, password|
  user == Settings.resque.user && password == Settings.resque.password
end
```

or just to make it work, type settings manually ;)

**Comment by ntulip** [comment]
@mensfeld Im sorry to be a pain but I am not sure how the answer fixes the "rake db:migrate" working.

**Comment by mensfeld** [comment]
Sorry - you aren't pain at all :)

When you perform migration you get error from resque init file, because the CONFIG constant doesn't work:

``` ruby
CONFIG[:redis][:host]
```

throws you:

``` ruby
You have a nil object when you didn't expect it!
```

because there is no CONFIG[:redis] object - the config parsing presented in config/initializers /config.rb doesn't seem to work anymore (or you don't have the config/redis_config.yml file). You might replace whole CONFIG management with additional gem like SettingsLogic. For now you can replace all the CONFIG refs with your config values like this:

``` ruby
require 'resque_scheduler'

Resque.redis = Redis.new(
  host: localhost,
  port: 6379,
  password: 'myredispassword',
  thread_safe: true
)

Resque::Server.use Rack::Auth::Basic do |user, password|
  user == 'login' && password == 'password'
end
```

**Ofc maybe that issue is not there anymore (since they fixed yaml parser) and the error comes from not having  redis_config.yml file. So first check  config/redis_config.yml file.**

**Comment by ntulip** [comment]
@mensfeld thank you! redis_config.yml was not there. Just the example. Rake worked! You're awesome.

**Comment by mensfeld** [comment]
Nice! :) I spent a bit of time with Pinger so if you have any other questions you can write to me ;) Austin seems to be busy right now so probably he will react to those issues a bit slowly.

**Comment by ntulip** [comment]
I appreciate it and will let you know. I am not out of the water yet. I went to run it with script/server and that doesn't exist. I installed passenger because of apache and i see that passenger allows you to run it inside the app as its own server.

**Comment by ntulip** [comment]
@mensfeld I have the app running through passenger. I've added a site to monitor but it doesn't seem that a resque worker is working. Pings are not taking place so that is broke. Any insight would be appreciated.

**Comment by mensfeld** [comment]
@ntulip: you need to run resque task for Pinger
